server:
  port: 8000

security:
  jwt:
    secret: "my-super-secret-jwt-key-my-super-secret-jwt-key"
    expiration-seconds: 3600
  auth:
    users:
      - username: user
        password: user123
        roles:
          - USER
      - username: admin
        password: admin123
        roles:
          - USER
          - ADMIN

zuul:
  routes:
    order:
      path: /api/order/**
      url: http://localhost:8001/
    users:
      path: /api/users/**
      url: http://localhost:8003/
    inventory:
      path: /api/inventory/**
      url: http://localhost:8004/